require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'oxy_pulse_tracker' do
  use_unimodules!(exclude: [
    'expo-constants',
    'expo-file-system',
    'expo-image-loader',
    'expo-permissions',
    'unimodules-face-detector-interface',
    'unimodules-file-system-interface',
    'unimodules-font-interface',
    'unimodules-image-loader-interface',
    'unimodules-permissions-interface',
    'unimodules-sensors-interface',
    'unimodules-task-manager-interface',
    'unimodules-barcode-scanner-interface',
    'unimodules-camera-interface',
  ])
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'oxy_pulse_trackerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end