import RNHTMLtoPDF from 'react-native-html-to-pdf';
import {Share} from 'react-native';
import {OxyPulseDataType} from '../models/member.interface';
import {getFormattedTableData} from './member.util';

const generateHTML = (member: OxyPulseDataType) => {
  const tableData = getFormattedTableData(member?.stat);
  return `
    <!DOCTYPE html>
    <html>
    <head>
    <style>
    #observations {
      font-family: Arial, Helvetica, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }

    #observations td, #observations th {
      border: 1px solid #ddd;
      padding: 8px;
    }

    #observations tr:nth-child(even){background-color: #f2f2f2;}

    #observations th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      background-color: #4CAF50;
      color: white;
      margin-bottom: 20px;
    }

    #observations td {
      text-align: center;
    }

    .footer {
      position: fixed;
      left: 0;
      bottom: 0;
      width: 100%;
      background-color: transparent;
      color: white;
      text-align: center;
    }

    #copyright > p {
      color: grey
    }

    .center {
      margin: auto;
      width: 100%;
      border: 3px solid green;
      padding: 10px;
      text-align: center;
    }
    </style>
    </head>
    <body>
    <header>
      <div>
        <p><b>Name</b>: ${member?.name ?? '-'}</p>
        <p><b>Age</b>: ${member?.age ?? '-'}</p>
        <p><b>Relation</b>: ${member?.relation ?? '-'}</p>
      </div>
    </header>
    </div class="center">
        <p style="color:grey;"><i><u>Generated by Oxy-Pulse Track Application</u></i></p>
      <div>
    <table id="observations">
      <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Oxygen Saturation (SpO<sub>2</sub>)</th>
        <th>Pulse Rate(bpm)</th>
        <th>Temperature(&deg;F)</th>
      </tr>
      ${tableData
        ?.map(data => {
          const [date, time, oxy_sat, pulse_rate, temperature] = data;
          return `<tr>
        <td>${date}</td>
        <td>${time}</td>
        <td>${oxy_sat || '-'}</td>
        <td>${pulse_rate || '-'}</td>
        <td>${temperature || '-'}</td>
      </tr>`;
        })
        ?.join('\n')}
    </table>
    </body>
    </html>
    `;
};

export const createPDF = async (member: OxyPulseDataType) => {
  const html = generateHTML(member);
  const options: RNHTMLtoPDF.Options = {
    html,
    fileName: `${member?.name}-${Date.now()}`,
    directory: 'Reports',
  };
  const file = await RNHTMLtoPDF.convert(options);
  return sharePDF(file);
};

const sharePDF = (file: RNHTMLtoPDF.Pdf) => {
  if (file) {
    Share.share({
      title: 'Download Observations PDF',
      url: file?.filePath as string,
    });
  }
};
